// Generated by dts-bundle-generator v9.5.1

export type Specification = {
	readonly "data-sketch": "1.0.0-draft.2";
	readonly info: {
		readonly name: string;
		readonly [extensionField: string]: unknown;
	};
	readonly sources?: {
		readonly openapi?: string;
		readonly arazzo?: string;
		readonly asyncapi?: string;
		readonly [extensionField: string]: unknown;
	};
	readonly claims: Readonly<Record<string, {
		readonly name: string;
		readonly reason: string;
		readonly traces: {
			readonly operations: readonly string[];
			readonly workflows?: readonly string[];
			readonly channels?: readonly string[];
			readonly [extensionField: string]: unknown;
		};
		readonly details?: readonly string[];
		readonly optionals?: Readonly<Record<string, boolean>>;
		readonly aliases?: Readonly<Record<string, readonly string[]>>;
		readonly relations?: Readonly<Record<string, string>>;
		readonly tentative?: boolean;
		readonly [extensionField: string]: unknown;
	}>>;
	readonly [extensionField: string]: unknown;
};
export type DataSketch = {
	readonly spec: Specification;
	readonly sources?: {
		readonly openapi?: unknown;
	};
	readonly metadata: {
		readonly version: string;
		readonly baseDirectoryPath: string;
		readonly validated?: boolean;
	};
};
export type ValidatedDataSketch = DataSketch & {
	readonly metadata: DataSketch["metadata"] & {
		readonly validated: true;
	};
};
export declare function parse(options: {
	readonly specFilePath: string;
} | {
	readonly specSourceText: string;
}): DataSketch;
export type RelationalDbProjection = {
	readonly "data-sketch/relational-db-projection": "1.0.0-draft.3";
	readonly tables: Readonly<Record<string, RelationalDbProjectionTable>>;
};
type RelationalDbProjectionTable = {
	readonly name: string;
	readonly columns: readonly RelationalDbProjectionColumn[];
	readonly keys: RelationalDbProjectionKeys;
	readonly constraints?: RelationalDbProjectionConstraints;
	readonly indexes?: readonly RelationalDbProjectionIndex[];
};
type RelationalDbProjectionKeys = {
	readonly primary: RelationalDbProjectionPrimaryKey;
	readonly foreign: readonly RelationalDbProjectionForeignKey[];
};
type RelationalDbProjectionColumn = {
	readonly id: string;
	readonly name: string;
	readonly type: RelationalDbProjectionColumnType;
	readonly nullable?: true;
};
type RelationalDbProjectionColumnType = `CHAR(${number})` | "VARCHAR(1024)" | `VARCHAR(${number})` | "INTEGER" | "BIGINT" | "DOUBLE PRECISION" | "BOOLEAN" | `DECIMAL(${number}, ${number})`;
type RelationalDbProjectionPrimaryKey = {
	readonly name: string;
	readonly columns: readonly string[];
};
type RelationalDbProjectionForeignKey = {
	readonly name: string;
	readonly column: string;
	readonly target: {
		readonly table: string;
		readonly column: string;
	};
	readonly kind: RelationalDbProjectionForeignKeyKind;
};
type RelationalDbProjectionForeignKeyKind = "explicit" | "structural" | "inferred" | "extension";
type RelationalDbProjectionConstraints = {
	readonly unique?: readonly RelationalDbProjectionUniqueConstraint[];
	readonly check?: readonly RelationalDbProjectionCheckConstraint[];
};
type RelationalDbProjectionUniqueConstraint = {
	readonly name: string;
	readonly columns: readonly string[];
};
type RelationalDbProjectionCheckConstraint = {
	readonly name: string;
	readonly column: string;
	readonly enum: readonly string[];
};
type RelationalDbProjectionIndex = {
	readonly name: string;
	readonly columns: readonly string[];
};
export type Projector<T = unknown> = {
	readonly name: string;
	readonly build: (context: ProjectionContext) => T;
};
export type ProjectionContext = {
	readonly sketch: ValidatedDataSketch;
	readonly projection: <T = unknown>(name: string) => T;
};
export type ProjectionResolver = {
	readonly get: <T = unknown>(name: string) => T;
};
export declare const relationalDbProjector: Projector<RelationalDbProjection>;
export declare function project(sketch: ValidatedDataSketch, projectors: readonly Projector[]): ProjectionResolver;
export declare function validateRelationalDbProjection(projection: RelationalDbProjection): void;
export declare function renderTablesDoc(spec: Specification, projection: RelationalDbProjection, sourceLabel: string): string;
export type ValidatorContext = {
	readonly sketch: DataSketch;
	readonly trace: boolean;
};
export type Validator = {
	readonly name: string;
	readonly validate: (context: ValidatorContext) => readonly string[];
};
export type ValidationSources = {
	readonly openapi?: unknown;
};
export type ValidateOptions = {
	readonly specFilePath: string;
	readonly trace?: boolean;
	readonly validators?: readonly Validator[];
} | {
	readonly sketch: DataSketch;
	readonly sources?: ValidationSources;
	readonly trace?: boolean;
	readonly validators?: readonly Validator[];
};
export declare const coreValidator: Validator;
export declare const openApiValidator: Validator;
export declare function validate(options: ValidateOptions): ValidatedDataSketch;

export {};
